### ISSUE TITLE
New-FreshServiceConnection - Fails to run on macOS (and presumably any non-Windows OS)

### ISSUE THREAD

**Issue by Siernan** [flycastpartnersinc/FreshservicePS#3]
New-FreshServiceConnection references the global variable "$FreshServiceConfigPath" (defined in FreshservicePS.psm1) which itself references "$env:APPDATA". "$env:APPDATA" is an environment variable that only exists on Windows. Since it doesn't exist, it generates the path string as "/FreshservicePS/FreshservicePS.config" which tries to write to the root directory and this fails due to permissions (as expected).

## Expected Behavior
New-FreshServiceConnection runs and creates config file in appropriate directory

## Current Behavior
New-FreshServiceConnection fails due to lack of $env:APPDATA directory on macOS

## Possible Solution
Include logic to detect non-Windows systems and reference an appropriate environment variable to store the config file in a suitable location.

## Steps to Reproduce (for bugs)
1. Install module in PowerShell Core on macOS
2. Run New-FreshServiceConnection cmdlet with required parameters
3. Error occurs (due to attempting to write to the root directory)

## Context
Would like to actually use the module on any system.

## Your Environment
* Module version used: FreshservicePS 0.1.3
* Operating System and PowerShell version: macOS 13.5.1, Powershell Core 7.3.6

**Comment by rasimmers** [comment]
Code merged.  Thank you for the contribution.

**Comment by Siernan** [comment]
> Code merged. Thank you for the contribution.

No problem @rasimmers .
Will you be updating it on the PSGallery as well?
