### ISSUE TITLE
Server Core - UseBasicParsing on Invoke-WebRequest/RESTRequest

### ISSUE THREAD

**Issue by JaibeHyne** [flycastpartnersinc/FreshservicePS#5]
When using Server Core with FreshservicePS we can't issue any commands without trigging the exception.
For server core doesn't have Internet Explorer Invoke-WebRequest or Invoke-RestMethod require the parameter -UseBasicParsing

## Current Behavior
Any issued FreshservicePS cmdlet on Server Core hits error exception. Exception message: 
"Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or
Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At C:\Program Files\WindowsPowerShell\Modules\FreshservicePS\0.1.3\Private\Invoke-FreshworksRestMethod.ps1"

## Possible Solution
Add optional parameter switch for UseBasicParsing on FreshservicePS cmdlets or alternatively check if running Server Core before issuing command and adjust parameters used in Invoke-FreshworksRestMethod.ps1 module.

## Context
We run a lot of Azure Automation from Server Core servers and want to use FreshservicePS on existing servers.

## Your Environment
* Module version used:  0.1.3 
* Operating System and PowerShell version: Server Core, PowerShell v5.1

**Comment by rasimmers** [comment]
Hi @JaibeHyne.  Can you provide the version of Powershell being run on those servers?  Based on the [docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.3#Notes), it appears that this parameter is deprecated in version 6 or higher and is the default.

_-UseBasicParsing
This parameter has been deprecated. Beginning with PowerShell 6.0.0, all Web requests use basic parsing only. This parameter is included for backwards compatibility only and any use of it has no effect on the operation of the cmdlet._

Not sure if the best route is detection of a PS version or if a option is provided in the New-FSConnection\Set-FSConnection to append the switch at runtime if $true.  If it's detection, what is the criteria for forcing this option?

**Comment by rasimmers** [comment]
After reviewing some other modules, it looks like it has been hardcoded to support backwards compatibility.  The Invoke-WebRequest will have the appended for all calls in Invoke-FreshworksRestMethod.

**Comment by rasimmers** [comment]
@JaibeHyne FreshservicePS 0.1.4 has been published and released with the update to -UseBasicParsing requested.

**Comment by rasimmers** [comment]
@JaibeHyne FreshservicePS 0.1.4 has been published and released with the update to -UseBasicParsing requested.
