### ISSUE TITLE
Allow for UTF-8 Charset in Content-Type

### ISSUE THREAD

**Issue by andersjens1** [flycastpartnersinc/FreshservicePS#7]
It would be nice if the invoke-FreshworksRestMethod.ps1 could also support Uutf-8 for json content.

$HTTPHeaders.Add('Content-Type', 'application/json; charset=utf-8')
istead of 
$HTTPHeaders.Add('Content-Type', 'application/json)

## Expected Behavior
This would help making it easier to create and update data containing special characters like German or Norwegian letters.

## Current Behavior
Today creation of tickets crash if the Description or Subject contains some of those characters.

## Possible Solution
$HTTPHeaders.Add('Content-Type', 'application/json; charset=utf-8')
istead of 
$HTTPHeaders.Add('Content-Type', 'application/json)
in 
invoke-FreshworksRestMethod.ps1

## Steps to Reproduce (for bugs)
Tro to create a new i.ex. Department with:
New-FreshServiceDepartment -name "Name Ø" 

## Context
We have a lot of names, company names etc. containing special characters, and replacing this worked as a charm.

## Your Environment
* Module version used: 0.1.3
* Operating System and PowerShell version: PS ver 5.0 on Win11

**Comment by rasimmers** [comment]
Looking at some other Powershell modules, that appears to be the default.  We will update the default and test the build.  Also see examples with the headers having a default as well to support UTF-8:

`"Accept-Charset" = "utf-8"`

**Comment by rasimmers** [comment]
@andersjens1 FreshservicePS 0.1.4 has been published and released with the update to support UTF-8 requested.
